const {app,BrowserWindow,ipcMain,dialog,clipboard,shell,Menu}=require('electron');const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const{Store,atomic}=require('./store.cjs');
if(process.env.REFMAN_USER_DATA)app.setPath('userData',process.env.REFMAN_USER_DATA);
let win,store,ai,word;const progress=value=>win?.webContents.send('refman-progress',value);
const getCitations=()=>require('./citations.cjs');const getAI=()=>ai ||= require('./ai.cjs');const getWord=()=>word ||= require('./word.cjs');
function recent(){try{return JSON.parse(fs.readFileSync(path.join(app.getPath('userData'),'recent.json'),'utf8'));}catch{return[];}}
function remember(){let list=recent().filter(x=>x.path!==store.folder);list.unshift({path:store.folder,name:store.project.name,id:store.project.id});atomic(path.join(app.getPath('userData'),'recent.json'),JSON.stringify(list.slice(0,30)));}
function checkActive(active){if(store!==active)throw Error('The project changed during this action. Retry in the intended project.');}
function needProject(){if(!store?.project)throw Error('Open or create a project first.');}
async function safeStatus(fn){try{return await fn();}catch(e){return{available:false,message:e.message};}}
async function save(p){needProject();if(p.id!==store.project.id)throw Error('The active project changed. Reopen the intended project before saving.');const project=await store.save(p);remember();return project;}
async function route(action,p={}){switch(action){
case'boot':return{projects:recent(),project:store?.project||null,aiStatus:await safeStatus(()=>getAI().status()),wordStatus:await safeStatus(()=>getWord().status())};
case'createProject':{const picked=await dialog.showOpenDialog(win,{title:'Choose where to keep your Refman project',properties:['openDirectory','createDirectory']});if(picked.canceled)return null;const name=String(p.name||'Untitled project').trim();const slug=name.replace(/[^a-zA-Z0-9 -]/g,'').trim().slice(0,60)||'Project';const folder=path.join(picked.filePaths[0],slug+'.refman');const next=new Store(folder);await next.create(name);store=next;remember();return store.project;}
case'openProject':{let folder=p.path;if(!folder){const picked=await dialog.showOpenDialog(win,{title:'Open a Refman project folder or restore project.txt',properties:['openFile','openDirectory'],filters:[{name:'Project backup',extensions:['txt','json','sqlite']}]});if(picked.canceled)return null;folder=picked.filePaths[0];}const stat=fs.statSync(folder);if(stat.isFile()){if(['.txt','.json'].includes(path.extname(folder))){const picked=await dialog.showOpenDialog(win,{title:'Choose a folder for the restored project',properties:['openDirectory','createDirectory']});if(picked.canceled)return null;const next=new Store(path.join(picked.filePaths[0],'Restored-'+Date.now()+'.refman'));await next.restoreFile(folder);store=next;remember();return store.project;}folder=path.dirname(folder);}const next=new Store(folder);await next.open();store=next;remember();return store.project;}
case'saveProject':return save(p.project);
case'lookup':return require('./intake.cjs').lookupSource(p.input);
case'attach':{needProject();const active=store;const picked=await dialog.showOpenDialog(win,{title:'Attach a source or Griffith rule screenshot',properties:['openFile'],filters:[{name:'Sources',extensions:['pdf','png','jpg','jpeg','webp','txt','docx']}]});if(picked.canceled)return null;checkActive(active);const result=await active.attach(p.sourceId,picked.filePaths[0]);checkActive(active);remember();return result;}
case'openAttachment':needProject();return shell.openPath(store.attachmentPath(p.path));
case'format':needProject();return getCitations().formatSource(store.project.sources.find(s=>s.id===p.sourceId),store.project);
case'bibliography':needProject();return getCitations().bibliography(store.project);
case'combined':needProject();return getCitations().combined(p.ids,store.project);
case'copy':clipboard.write({text:String(p.text||''),...(p.html?{html:p.html}:{})});return{ok:true};
case'aiStatus':return getAI().status();
case'aiLogin':return getAI().login();
case'aiChat':{needProject();const activeStore=store;const target=structuredClone(store.project);for(const source of target.sources)for(const a of source.attachments||[])try{a.path=activeStore.attachmentPath(a.path);}catch{a.missing=true;a.path='';}const result=await getAI().chat({project:target,sourceId:p.sourceId,message:p.message,mode:p.mode},progress);if(store!==activeStore)throw Error('The project changed while GPT was responding. Reopen the original project and retry.');const project=structuredClone(store.project);project.chat ||= [];project.chat.push({role:'user',content:p.message||'Summarise this source for my essay',at:new Date().toISOString(),sourceId:p.sourceId},{role:'assistant',content:result.reply,at:new Date().toISOString(),sourceId:p.sourceId});if(p.mode==='summary'){const source=project.sources.find(s=>s.id===p.sourceId);if(source){source.history ||= [];source.history.push({at:new Date().toISOString(),reason:'Previous summary',summary:source.summary||''});source.summary=result.reply;source.summaryContext=crypto.createHash('sha256').update([target.question,target.rubric,target.draft].join('\n')).digest('hex');source.summaryNeedsRefresh=source.summaryContext!==crypto.createHash('sha256').update([project.question,project.rubric,project.draft].join('\n')).digest('hex');}}return{...result,project:await save(project)};}
case'applyProposal':{needProject();const proposal=p.proposal;if(!proposal?.sourceId||!proposal.changes)throw Error('No source correction to apply.');const project=structuredClone(store.project),source=project.sources.find(s=>s.id===proposal.sourceId);if(!source)throw Error('The source no longer exists.');const allowed=['type','authors','year','date','title','container','volume','issue','pages','publisher','edition','doi','url','retrieved','abbreviation','jurisdiction','subdivision','country','editors','reportNumber','overrides','missing','verification'];const changes={};for(const[key,value]of Object.entries(proposal.changes))if(allowed.includes(key))changes[key]=value;source.history ||= [];source.history.push({at:new Date().toISOString(),reason:proposal.reason||'GPT correction accepted',before:Object.fromEntries(Object.entries(structuredClone(source)).filter(([key])=>key!=='history')),changes});if(changes.overrides)changes.overrides={...source.overrides,...changes.overrides};Object.assign(source,changes);return save(project);}
case'wordStatus':return getWord().status();
case'wordInsert':return getWord().insert(p.text);
case'wordUpdate':{needProject();const active=store;const b=getCitations().bibliography(store.project);if(!b.entries.length)throw Error('Select at least one source for your reference list.');const state=store.project.wordState||{};let result=await getWord().update({...p,text:b.text,html:b.html,expectedHash:state.hash});checkActive(active);if(result.needsConfirmation){const answer=await dialog.showMessageBox(win,{type:'warning',title:'Review Word changes',message:'The References section has manual changes, or needs to be created.',detail:result.message||'Updating will replace only the identified reference content. Keep manual reference corrections in Refman to preserve them.',buttons:['Cancel','Update References'],defaultId:0,cancelId:0});if(answer.response!==1)return{canceled:true};checkActive(active);result=await getWord().update({...p,text:b.text,html:b.html,expectedHash:result.expectedHash||result.hash,confirmed:true});}checkActive(active);if(result.needsConfirmation)throw Error(result.message||'Word changed again. Please review and retry.');if(result.updated===true&&result.hash){const project=structuredClone(store.project);project.wordState={hash:result.hash,document:result.document,at:new Date().toISOString()};await save(project);}return result;}
case'auditWord':{needProject();const result=await getWord().audit();return{...result,analysis:require('./audit.cjs').auditText(result.documentText||'',store.project),referenceSources:store.project.sources.filter(s=>s.include).map(s=>({id:s.id,title:s.title,citation:getCitations().formatSource(s,store.project).parenthetical})),notice:'Plain-text matching is advisory. Confirm ambiguous matches and check whether claims are supported by the full source.'};}
case'exportDocx':{needProject();const active=store;const b=getCitations().bibliography(active.project);const picked=await dialog.showSaveDialog(win,{title:'Export references for Word',defaultPath:'References.docx',filters:[{name:'Word document',extensions:['docx']}]});if(picked.canceled)return null;checkActive(active);if(getWord().exportDocx)return getWord().exportDocx({...p,...b},picked.filePath);throw Error('Word export is not ready.');}
case'backups':needProject();return store.backups();
case'restore':{needProject();const active=store;const answer=await dialog.showMessageBox(win,{type:'question',message:'Restore this earlier version?',detail:'Your current version will be saved before restoring.',buttons:['Cancel','Restore'],cancelId:0,defaultId:0});if(answer.response===0)return null;checkActive(active);const project=await active.restore(p.name);checkActive(active);remember();return project;}
case'revealProject':needProject();shell.showItemInFolder(path.join(store.folder,'project.txt'));return{ok:true};
default:throw Error('Unknown action: '+action);}}
app.whenReady().then(async()=>{fs.mkdirSync(app.getPath('userData'),{recursive:true});win=new BrowserWindow({width:1440,height:920,minWidth:1060,minHeight:720,title:'Refman',backgroundColor:'#f5f3ee',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});Menu.setApplicationMenu(Menu.buildFromTemplate([{label:'Refman',submenu:[{role:'about'},{type:'separator'},{role:'quit'}]},{label:'Edit',submenu:[{role:'undo'},{role:'redo'},{type:'separator'},{role:'cut'},{role:'copy'},{role:'paste'},{role:'selectAll'}]},{label:'View',submenu:[{role:'reload'},{role:'toggleDevTools'},{role:'resetZoom'},{role:'zoomIn'},{role:'zoomOut'}]},{label:'Window',submenu:[{role:'minimize'},{role:'zoom'}]}]));ipcMain.handle('refman',async(event,action,payload)=>{if(event.sender!==win.webContents)throw Error('Untrusted window.');return route(action,payload);});win.webContents.setWindowOpenHandler(({url})=>{if(/^https?:\/\//.test(url))shell.openExternal(url);return{action:'deny'};});win.webContents.on('will-navigate',(event,url)=>{if(!url.startsWith('file://'))event.preventDefault();});if(process.env.REFMAN_TEST_PROJECT){store=new Store(process.env.REFMAN_TEST_PROJECT);await store.open();}await win.loadFile(path.join(__dirname,'index.html'));});
app.on('window-all-closed',()=>app.quit());
