'use strict';
(() => {
  const $ = id => document.getElementById(id);
  const all = selector => [...document.querySelectorAll(selector)];
  const clone = value => structuredClone(value);
  const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
  const state = {project:null, projects:[], selected:null, dirty:false, revision:0, saveTimer:null, saveChain:Promise.resolve(), format:null, bibliography:null, combined:'', ids:new Set(), proposal:null, aiBusy:false};
  const labels = {journal:'Journal article',book:'Book',chapter:'Book chapter',webpage:'Webpage',report:'Report',thesis:'Thesis',conference:'Conference paper',newspaper:'Newspaper',uptodate:'UpToDate',emims:'eMIMSelite',mims:'MIMS',legislation:'Legislation',bill:'Bill',case:'Legal case',cochrane:'Cochrane review',clinical:'Clinical database',other:'Other'};
  const typeAliases = {emimselite:'emims',article:'journal','journal-article':'journal','article-journal':'journal',web:'webpage',website:'webpage','book-chapter':'chapter',drug:'clinical','clinical-database':'clinical','systematic-review':'cochrane',statute:'legislation','legal-case':'case',government:'report','government-report':'report','newspaper-article':'newspaper'};
  const sourceType = type => typeAliases[type]||type||'journal';
  const fields = ['type','year','date','country','title','container','volume','issue','pages','edition','publisher','doi','url','retrieved','abbreviation','jurisdiction','subdivision','reportNumber'];
  const briefFields = ['name','question','rubric','draft','minYear','maxYear','rules'];
  let toastTimer, combinedRequest=0, aiPollTimer, summaryContextRequest=0;
  const source = () => state.project?.sources?.find(item => item.id === state.selected);
  function node(tag, text, className) {const item=document.createElement(tag); if(text!==undefined)item.textContent=text;if(className)item.className=className;return item;}
  function toast(message, error=false) {$('toast').textContent=message;$('toast').classList.toggle('error',error);$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('toast').hidden=true;},error?9000:4500);}
  async function invoke(action,payload={}) {if(!window.refman?.invoke)throw Error('Refman must be opened in its desktop app.');return window.refman.invoke(action,payload);}
  function bind(id,fn) {$(id).addEventListener('click',()=>run($(id),fn));}
  async function run(button,fn) {if(button?.disabled)return;const old=button?.textContent;if(button){button.disabled=true;button.setAttribute('aria-busy','true');}try{return await fn();}catch(error){toast(error.message||String(error),true);}finally{if(button){button.disabled=false;button.removeAttribute('aria-busy');if(old&&!button.textContent)button.textContent=old;}}}
  function status(message) {$('save-status').textContent=message;}
  function authorsText(authors=[]) {return authors.map(a=>a.literal?'='+a.literal:[a.family,a.given].filter(Boolean).join(', ')).join('\n');}
  function parseAuthors(text) {return text.split('\n').map(s=>s.trim()).filter(Boolean).map(s=>{if(s.startsWith('='))return {literal:s.slice(1).trim()};const comma=s.indexOf(',');return comma<0?{family:s,given:''}:{family:s.slice(0,comma).trim(),given:s.slice(comma+1).trim()};});}
  function currentMissing(s) {const required=['legislation','bill','case'].includes(sourceType(s.type))?['title','year']:['title','authors','year'];const missing=required.filter(key=>key==='authors'?!(s.authors||[]).some(a=>String(a?.family||a?.literal||'').trim()):!String(s[key]||'').trim());if(['journal','article','chapter'].includes(sourceType(s.type))&&!String(s.container||'').trim())missing.push('container');const extra=(s.missing||[]).filter(key=>!['title','authors','year','container'].includes(key)&&!(Object.hasOwn(s,key)&&String(s[key]??'').trim()));return [...new Set([...missing,...extra])];}
  function evidenceRecords(s) {return [...new Map([...(s?.verification||[]),...(s?.evidence||[])].map(item=>[JSON.stringify(item),item])).values()];}
  function renderVerification(s) {const records=evidenceRecords(s),providers=[...new Set(records.map(item=>typeof item==='string'?'Import record':item.provider||item.source||'Import record'))];$('source-verification').textContent=records.length?providers.join(', ')+' · '+records.length+' evidence '+(records.length===1?'record':'records'):'Editable source record';$('view-evidence').hidden=!records.length;}
  function renderEvidence() {
    const s=source();$('evidence-list').replaceChildren();
    for(const item of evidenceRecords(s)){
      const row=node('section',undefined,'evidence-record');
      if(typeof item==='string'){row.append(node('p',item));$('evidence-list').append(row);continue;}
      row.append(node('h3',item.field||'Metadata check'),node('p',item.provider||item.source||'Imported evidence','muted'));
      let value=item.value;
      if(Array.isArray(value))value=value.map(part=>typeof part==='object'?part.literal||[part.family,part.given].filter(Boolean).join(', '):String(part)).join('; ');
      else if(value&&typeof value==='object')value=Object.entries(value).map(([key,entry])=>key+': '+String(entry)).join(' · ');
      if(value!==undefined)row.append(node('p',String(value),'evidence-value'));
      if(item.note||item.message)row.append(node('p',item.note||item.message,'muted'));
      if(item.checkedAt)row.append(node('p','Recorded '+new Date(item.checkedAt).toLocaleString(),'muted'));
      if(item.field&&Object.hasOwn(s,item.field)&&!same(s[item.field],item.value))row.append(node('p','Current value has been edited since this import.','evidence-edited'));
      try{const url=new URL(item.url);if(['https:','http:'].includes(url.protocol)){const link=node('a','View original evidence ↗','text-button');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer';row.append(link);}}catch{}
      $('evidence-list').append(row);
    }
    $('evidence-dialog').showModal();
  }
  function authorLine(s) {const authors=(s.authors||[]).map(a=>a.literal||a.family||'').filter(Boolean);return [authors.length>2?authors[0]+' et al.':authors.join(' & '),s.year||'n.d.'].filter(Boolean).join(' · ');}
  function markDirty() {state.dirty=true;state.revision++;state.format=null;state.bibliography=null;status('Unsaved changes');clearTimeout(state.saveTimer);state.saveTimer=setTimeout(()=>save().catch(e=>toast('Could not save: '+e.message,true)),850);}
  function captureSource() {const s=source();if(!s)return;const form=$('metadata-form');for(const f of fields)s[f]=form.elements.namedItem(f).value;s.authors=parseAuthors(form.elements.namedItem('authorsText').value);s.editors=parseAuthors(form.elements.namedItem('editorsText').value);s.notes=$('source-notes').value;s.summary=$('source-summary').value;s.content=$('source-content').value;s.overrides={...(s.overrides||{}),reference:$('override-reference').value,parenthetical:$('override-parenthetical').value,narrative:$('override-narrative').value};s.missing=currentMissing(s);}
  function captureBrief() {if(!state.project)return;for(const f of briefFields){const value=$('brief-form').elements.namedItem(f).value;state.project[f]=(f==='minYear'||f==='maxYear')?(value?Number(value):null):value;}}
  function capture() {captureSource();captureBrief();}
  function recordChanges(project) {for(const s of project.sources){const previous=state.saved?.sources?.find(old=>old.id===s.id);if(!previous)continue;const changes={};for(const key of [...fields,'authors','editors','notes','summary','content','overrides','include','missing'])if(!same(s[key],previous[key]))changes[key]={before:previous[key]??'',after:s[key]??''};if(Object.keys(changes).length){s.history ||= [];s.history.push({at:new Date().toISOString(),reason:'Edited in Refman',changes});}}}
  async function save(force=false) {if(!state.project)return null;capture();clearTimeout(state.saveTimer);const currentId=state.project.id;const work=async()=>{if(state.project?.id!==currentId)return null;if(!state.dirty&&!force)return state.project;const revision=state.revision;const snapshot=clone(state.project);recordChanges(snapshot);status('Saving…');try{const result=await invoke('saveProject',{project:snapshot});if(state.project?.id===currentId){state.saved=clone(result||snapshot);if(state.revision===revision){state.project=result||snapshot;state.dirty=false;status('Saved locally');showSummaryWarning();}else{for(const s of state.project.sources){const savedSource=state.saved.sources.find(x=>x.id===s.id);if(savedSource)s.history=savedSource.history;}status('Unsaved changes');}renderProjects();}return result;}catch(error){status('Save failed · retry Save now');throw error;}};state.saveChain=state.saveChain.catch(()=>{}).then(work);return state.saveChain;}
  function normalize(project) {project.sources ||= [];project.chat ||= [];for(const s of project.sources){s.type=sourceType(s.type);s.authors ||= [];s.editors ||= [];s.attachments ||= [];s.history ||= [];s.overrides ||= {};s.include=s.include===true;}const minimum=Math.max(0,...project.sources.map(s=>Number(s.number)||0))+1;project.nextSourceNumber=Math.max(minimum,Number.isSafeInteger(project.nextSourceNumber)?project.nextSourceNumber:1);return project;}
  function setProject(project) {if(!project)return;clearTimeout(state.saveTimer);state.project=normalize(project);state.saved=clone(state.project);state.selected=project.sources[0]?.id||null;state.dirty=false;state.revision++;state.ids.clear();state.format=null;state.bibliography=null;state.combined='';state.proposal=null;$('proposal').hidden=true;$('combined-output').textContent='Choose one or more sources.';$('bibliography-preview').textContent='Refresh to view this project’s reference list.';$('bibliography-warnings').hidden=true;$('word-report').hidden=true;render();status('Saved locally');refreshProjects().catch(()=>{});if(document.querySelector('.tab[data-view="citations"]').classList.contains('active'))run(null,refreshBibliography);}
  async function refreshProjects() {const boot=await invoke('boot');state.projects=boot.projects||[];renderProjects();}
  function renderProjects() {$('projects').replaceChildren();for(const project of state.projects){const button=node('button',undefined,'project-item');button.classList.toggle('active',project.id===state.project?.id);button.append(node('span','▤','project-icon'),node('span',project.id===state.project?.id?state.project.name:project.name,'project-name'));button.title=project.path;button.addEventListener('click',()=>run(button,async()=>{if(state.aiBusy)throw Error('Wait for the current GPT request before switching projects.');await save();const next=await invoke('openProject',{path:project.path});if(next)setProject(next);}));$('projects').append(button);}if(!state.projects.length)$('projects').append(node('p','Your projects will appear here.','muted'));}
  function render() {const active=!!state.project;$('workspace').hidden=!active;$('empty-project').hidden=active;$('project-title').textContent=state.project?.name||'Welcome to Refman';const recovery=state.project?.recoveryWarnings||[];$('recovery-warning').hidden=!recovery.length;$('recovery-warning').textContent=recovery.join(' · ');for(const id of ['save-project','backup-open','reveal-project'])$(id).disabled=!active;renderProjects();if(!active)return;for(const f of briefFields)$('brief-form').elements.namedItem(f).value=state.project[f]??'';renderWordFormatting();renderSources();renderDetail();renderChat();renderCitationSources();}
  function renderSources() {const sources=state.project?.sources||[];const query=$('source-search').value.trim().toLowerCase();$('source-count').textContent=sources.length;$('included-count').textContent=sources.filter(s=>s.include).length+' included in bibliography';$('sources').replaceChildren();for(const s of sources.filter(s=>[s.title,authorLine(s),s.notes,s.number].join(' ').toLowerCase().includes(query))){const row=node('div',undefined,'source-row');row.classList.toggle('active',s.id===state.selected);row.tabIndex=0;row.setAttribute('role','button');row.setAttribute('aria-label','Open source '+s.number+': '+(s.title||'Untitled source'));const info=node('div',undefined,'source-info');info.append(node('h3',s.title||'Untitled source'),node('p',authorLine(s)||'Add publication details'),node('span',labels[s.type]||s.type||'Other','source-type'));const check=node('input');check.type='checkbox';check.className='include-check';check.checked=s.include;check.setAttribute('aria-label','Include source '+s.number+' in bibliography');check.addEventListener('click',e=>e.stopPropagation());check.addEventListener('change',()=>{capture();const current=state.project.sources.find(item=>item.id===s.id);if(!current)return;current.include=check.checked;markDirty();renderSources();renderCitationSources();});row.append(node('span',String(s.number).padStart(2,'0'),'source-number'),info,check);const select=()=>{capture();state.selected=s.id;state.format=null;renderSources();renderDetail();};row.addEventListener('click',select);row.addEventListener('keydown',e=>{if(e.target===row&&(e.key==='Enter'||e.key===' ')){e.preventDefault();select();}});$('sources').append(row);}if(!sources.length)$('sources').append(node('p','No sources yet. Add your first reading.','list-empty'));else if(!$('sources').children.length)$('sources').append(node('p','No matching sources.','list-empty'));}
  function showWarnings(s,extra=[]) {
    if(!s)return;
    const missing=(s.missing||[]).filter(key=>!(key==='authors'?s.authors?.length:Object.hasOwn(s,key)&&String(s[key]??'').trim()));
    const messages=[...missing.map(x=>'Missing: '+x),...(s.warnings||[]),...extra];
    const year=String(s.year||'').trim();
    if(!year&&!missing.includes('year'))messages.push('Missing: publication year. Use n.d. only when the source has no date.');
    if(/^\d{4}$/.test(year)){
      if(state.project.minYear&&Number(year)<state.project.minYear)messages.push('Publication predates your project date range.');
      if(state.project.maxYear&&Number(year)>state.project.maxYear)messages.push('Publication is outside your project date range.');
    }
    $('source-warnings').hidden=!messages.length;$('source-warnings').textContent=[...new Set(messages.map(x=>typeof x==='string'?x:JSON.stringify(x)))].join(' · ');
  }
  function showSummaryWarning() {const selected=source();const stale=!!(String(selected?.summary||'').trim()&&selected.summaryNeedsRefresh);$('summary-warning').hidden=!stale;$('summary-warning').textContent='Your assignment context has changed since this summary was created. Review it or generate a new summary for your current brief.';}
  async function refreshSummaryContextFlags() {
    if(!state.project)return;
    const request=++summaryContextRequest,projectId=state.project.id;
    const context=[state.project.question,state.project.rubric,state.project.draft].join('\n');
    let hash;
    try{const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(context));hash=[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('');}catch{return;}
    if(request!==summaryContextRequest||state.project?.id!==projectId||[state.project.question,state.project.rubric,state.project.draft].join('\n')!==context)return;
    for(const item of state.project.sources){if(!String(item.summary||'').trim())item.summaryNeedsRefresh=false;else if(item.summaryContext)item.summaryNeedsRefresh=item.summaryContext!==hash;}
    showSummaryWarning();
  }

  function renderDetail() {const s=source();$('source-detail').hidden=!s;$('source-empty').hidden=!!s;if(!s){$('chat-context').textContent='PROJECT CONTEXT';return;}$('source-label').textContent='SOURCE '+String(s.number).padStart(2,'0');$('source-title').textContent=s.title||'Untitled source';$('source-byline').textContent=authorLine(s);const form=$('metadata-form');for(const f of fields){const el=form.elements.namedItem(f);if(f==='type'&&s[f]&&!labels[s[f]]&&!all('#metadata-form option').some(o=>o.value===s[f]))el.append(new Option(s[f],s[f]));el.value=s[f]??(f==='type'?'journal':'');}form.elements.namedItem('authorsText').value=authorsText(s.authors);form.elements.namedItem('editorsText').value=authorsText(s.editors);$('source-notes').value=s.notes||'';$('source-summary').value=s.summary||'';showSummaryWarning();$('source-content').value=s.content||'';for(const f of ['reference','parenthetical','narrative'])$('override-'+f).value=s.overrides?.[f]||'';showWarnings(s);renderVerification(s);$('chat-context').textContent='SOURCE '+s.number+' · '+(s.title||'Untitled');renderAttachments();renderHistory();$('reference-preview').textContent='Select Refresh to format the latest source details.';$('parenthetical-preview').textContent='—';$('narrative-preview').textContent='—';$('first-citations').hidden=true;if(document.querySelector('[data-detail="preview"]').classList.contains('active'))run(null,refreshFormat);}
  function renderAttachments() {
    $('attachments').replaceChildren();
    for(const a of source()?.attachments||[]){
      const row=node('div',undefined,'attachment'),info=node('div',undefined,'source-info');
      info.append(node('span','▱  '+(a.name||a.originalName||a.filename||a.path||'Attachment')));
      const missing=a.missing===true||!a.path;
      if(missing)info.append(node('p','Missing file. Restore the companion attachments folder or attach the original again.','muted'));
      if(a.extractionWarning)info.append(node('p','Text extraction: '+a.extractionWarning,'muted'));
      else if(a.contentBasis)info.append(node('p',a.contentBasis+(a.extractedPages?' · '+a.extractedPages+' pages':''),'muted'));
      const open=node('button',missing?'Missing file':'Open ↗','text-button');open.disabled=missing;
      open.addEventListener('click',()=>run(open,async()=>{const error=await invoke('openAttachment',{path:a.path});if(typeof error==='string'&&error)throw Error(error);}));
      row.append(info,open);$('attachments').append(row);
    }
    if(!$('attachments').children.length)$('attachments').append(node('p','No attachments yet.','muted'));
  }
  function renderHistory() {$('source-history').replaceChildren();for(const item of [...(source()?.history||[])].reverse()){const row=node('div',undefined,'history-item');row.append(node('div',item.at?new Date(item.at).toLocaleString():'Saved correction','date'),node('strong',item.reason||'Source updated'));if(item.changes)row.append(node('pre',JSON.stringify(item.changes,null,2)));else if(item.summary!==undefined)row.append(node('p',item.summary||'No previous summary.'));$('source-history').append(row);}if(!$('source-history').children.length)$('source-history').append(node('p','No corrections saved yet.','muted'));}
  function safeHtml(html,fallback) {const container=node('div');const parsed=new DOMParser().parseFromString(String(html||''),'text/html');const allowed=new Set(['P','DIV','SPAN','EM','I','STRONG','B','BR','SUP','SUB']);function copyTree(parent,target){for(const child of parent.childNodes){if(child.nodeType===Node.TEXT_NODE)target.append(document.createTextNode(child.textContent));else if(child.nodeType===Node.ELEMENT_NODE&&allowed.has(child.tagName)){const clean=node(child.tagName.toLowerCase());copyTree(child,clean);target.append(clean);}else if(child.nodeType===Node.ELEMENT_NODE&&!['SCRIPT','STYLE','IFRAME','OBJECT'].includes(child.tagName)){copyTree(child,target);}}}copyTree(parsed.body,container);if(!container.textContent.trim())container.textContent=fallback||'';return container;}
  async function refreshFormat() {const s=source();if(!s)return;await save();const selected=s.id,revision=state.revision;const formatted=await invoke('format',{sourceId:selected});if(state.selected!==selected||state.revision!==revision)return;state.format=formatted;$('reference-preview').replaceChildren(safeHtml(formatted.referenceHtml,formatted.reference));$('parenthetical-preview').textContent=formatted.parenthetical||'—';$('narrative-preview').textContent=formatted.narrative||'—';const first=[];if(formatted.firstParenthetical&&formatted.firstParenthetical!==formatted.parenthetical)first.push('First parenthetical citation: '+formatted.firstParenthetical);if(formatted.firstNarrative&&formatted.firstNarrative!==formatted.narrative)first.push('First narrative citation: '+formatted.firstNarrative);$('first-citations').textContent=first.join('\n');$('first-citations').hidden=!first.length;showWarnings(source(),formatted.warnings||[]);}
  function renderCitationSources() {$('citation-sources').replaceChildren();for(const s of state.project?.sources||[]){const label=node('label',undefined,'citation-source-choice');const check=node('input');check.type='checkbox';check.checked=state.ids.has(s.id);check.addEventListener('change',()=>{if(check.checked)state.ids.add(s.id);else state.ids.delete(s.id);run(null,refreshCombined);});const text=node('span',s.title||'Untitled source');text.append(node('small','#'+s.number+' · '+authorLine(s)));label.append(check,text);$('citation-sources').append(label);}if(!$('citation-sources').children.length)$('citation-sources').append(node('p','Add sources to build a citation.','muted'));}
  async function refreshCombined() {const request=++combinedRequest;await save();const ids=[...state.ids].filter(id=>state.project.sources.some(s=>s.id===id));const combined=ids.length?await invoke('combined',{ids}):'';if(request!==combinedRequest)return;state.combined=combined;$('combined-output').textContent=combined||'Choose one or more sources.';}
  async function refreshBibliography() {await save();state.bibliography=await invoke('bibliography');$('bibliography-preview').replaceChildren(safeHtml(state.bibliography.html,state.bibliography.text||'Select Include on a source to add it to your reference list.'));renderBibliographyWarnings(state.bibliography);return state.bibliography;}
  function bibliographyWarningGroups(bibliography) {
    return (bibliography.entries||[]).map(entry=>{const s=state.project.sources.find(item=>item.id===entry.id);const warnings=[...(entry.warnings||[]),...(s?.warnings||[]),...currentMissing(s||{}).map(field=>'Missing: '+field)];for(const evidence of evidenceRecords(s)){if(typeof evidence==='object'&&['failed','unverified','error'].includes(evidence.status))warnings.push(evidence.message||evidence.note||'Verification needs review for '+(evidence.field||'this source'));}return {id:entry.id,number:entry.number,title:s?.title||'Untitled source',warnings:[...new Set(warnings.map(value=>typeof value==='string'?value:value.message||String(value)))]};}).filter(group=>group.warnings.length);
  }
  function openSourceForReview(id) {capture();state.selected=id;state.format=null;all('.detail-tabs button').forEach(button=>button.classList.toggle('active',button.dataset.detail==='metadata'));all('.detail-page').forEach(page=>page.classList.toggle('active',page.dataset.page==='metadata'));renderSources();renderDetail();document.querySelector('.tab[data-view="library"]').click();}
  function warningGroupNode(group,canOpen=false) {const section=node('section',undefined,'reference-warning-group');const heading=node('div',undefined,'label-action');heading.append(node('strong','Source '+group.number+' · '+group.title));if(canOpen){const open=node('button','Review source ↗','text-button');open.addEventListener('click',()=>openSourceForReview(group.id));heading.append(open);}section.append(heading);const list=node('ul');for(const warning of group.warnings)list.append(node('li',warning));section.append(list);return section;}
  function renderBibliographyWarnings(bibliography) {const groups=bibliographyWarningGroups(bibliography);const target=$('bibliography-warnings');target.hidden=!groups.length;target.replaceChildren();if(!groups.length)return;target.append(node('h3','Review '+groups.length+' '+(groups.length===1?'source':'sources')+' before using this list'));for(const group of groups)target.append(warningGroupNode(group,true));}
  async function reviewBibliography(bibliography,action) {const groups=bibliographyWarningGroups(bibliography);if(!groups.length)return true;const review=node('div',undefined,'reference-review');review.append(node('p','Check these entries against the original publications. An absent date or an intentional override can be valid; continue once you have reviewed the warnings.','muted'));for(const group of groups)review.append(warningGroupNode(group));return confirmAction('Review reference warnings',review,action,'Return to review');}
  async function copy(text,html) {if(!text)throw Error('There is no citation to copy yet.');await invoke('copy',{text,html});toast('Copied to clipboard.');}
  function renderChat() {const messages=state.project?.chat||[];if(!messages.length){$('chat-messages').replaceChildren();const intro=node('div',undefined,'chat-intro');intro.append(node('span','✦'),node('h3','Think it through.'),node('p','Ask about your sources, refine an argument, or suggest a metadata correction. You review changes before applying them.'));$('chat-messages').append(intro);return;}$('chat-messages').replaceChildren();for(const message of messages){const card=node('div',undefined,'chat-message '+(message.role==='user'?'user':''));card.append(node('span',message.role==='user'?'You':'GPT','chat-message-label'),document.createTextNode(message.content||message.text||''));$('chat-messages').append(card);}$('chat-messages').scrollTop=$('chat-messages').scrollHeight;}
  function mergeRemote(remote,base) {capture();const local=state.project;if(!remote||local.id!==base.id)return;const remoteBaseline=clone(remote);for(const key of Object.keys(local)){if(['sources','chat'].includes(key))continue;if(!same(local[key],base[key]))remote[key]=clone(local[key]);}for(const original of base.sources){const edited=local.sources.find(s=>s.id===original.id);const updated=remote.sources.find(s=>s.id===original.id);if(!edited){remote.sources=remote.sources.filter(s=>s.id!==original.id);continue;}if(updated)for(const key of Object.keys(edited))if(key!=='history'&&!same(edited[key],original[key]))updated[key]=clone(edited[key]);}for(const added of local.sources)if(!base.sources.some(s=>s.id===added.id))remote.sources.push(clone(added));state.project=normalize(remote);state.saved=remoteBaseline;state.format=null;state.bibliography=null;render();}
  async function chat(mode='chat',suppliedMessage) {if(state.aiBusy)throw Error('GPT is already responding.');if(!state.project)throw Error('Open a project first.');const message=mode==='summary'?'Summarise this source for my research question, using the supplied source content. Identify limitations and keep claims tied to the source.':(suppliedMessage||$('chat-input').value.trim());if(!message)return;if(mode==='summary'&&!source())throw Error('Select a source to summarize.');await save();const base=clone(state.project);const sourceId=state.selected;state.aiBusy=true;$('chat-send').disabled=true;$('summarize').disabled=true;$('extract-details').disabled=true;$('ai-status').textContent='GPT is working…';try{const result=await invoke('aiChat',{message,sourceId,mode});mergeRemote(result.project,base);if(mode==='chat'&&!suppliedMessage)$('chat-input').value='';if(result.proposal){state.proposal=result.proposal;$('proposal-content').textContent=JSON.stringify(result.proposal.changes||result.proposal,null,2);$('proposal').hidden=false;}markDirty();await save();if(mode==='summary'){all('.detail-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.detail==='reading'));all('.detail-page').forEach(p=>p.classList.toggle('active',p.dataset.page==='reading'));}toast(mode==='summary'?'Summary saved. Review it against the original source.':'GPT response saved.');}finally{state.aiBusy=false;$('chat-send').disabled=false;$('summarize').disabled=false;$('extract-details').disabled=false;try{showAIStatus(await invoke('aiStatus'));}catch{$('ai-status').textContent='Check GPT connection';}}}
  function showAIStatus(result) {$('ai-status').textContent=result?.message||(result?.authenticated||result?.loggedIn||result?.connected?'Connected to GPT':result?.available?'Connect your GPT account':'GPT connection unavailable');}
  function watchAIConnection() {
    clearTimeout(aiPollTimer);const deadline=Date.now()+180000;
    const check=async()=>{try{const result=await invoke('aiStatus');showAIStatus(result);if(result?.pending&&Date.now()<deadline)aiPollTimer=setTimeout(check,3000);}catch(error){$('ai-status').textContent='Use the connection button to refresh sign-in status.';}};
    aiPollTimer=setTimeout(check,2500);
  }
  function renderAudit(result) {
    const target=$('word-report');target.hidden=false;target.replaceChildren(node('h3','Document check'));
    target.append(node('p',result.document||'Your Word draft','muted'));
    const analysis=result.analysis;
    if(!analysis){target.append(node('p',result.note||'Review these detected citation candidates against your source library.','muted'));const list=node('ul');for(const citation of result.citations||[])list.append(node('li',typeof citation==='string'?citation:citation.text||''));if(list.children.length)target.append(list);else target.append(node('p','No citation candidates detected. Review narrative citations manually.','muted'));return;}
    const summary=analysis.summary||{};
    const counts=node('div',undefined,'audit-counts');
    for(const [key,label] of [['matchedSources','Cited sources matched'],['unmatchedCitations','Citations to review'],['uncitedSelected','Selected sources not detected'],['notIncluded','Cited sources excluded'],['ambiguous','Ambiguous matches']]){const card=node('div');card.append(node('strong',String(summary[key]??analysis[key]?.length??0)),node('span',label));counts.append(card);}target.append(counts);
    const sections=[['notIncluded','Cited sources excluded from your reference list'],['unmatchedCitations','Citations without a clear library match'],['ambiguous','Matches that need your review'],['uncitedSelected','Selected references without a detected citation'],['matched','Matched citations']];
    for(const [key,title] of sections){const items=analysis[key]||[];if(!items.length)continue;const section=node('section',undefined,'audit-section');section.append(node('h3',title));for(const item of items){const row=node('div',undefined,'audit-row');const description=node('div');if(item.text)description.append(node('strong',item.text));if(item.title)description.append(node('p',item.title));if(item.citation&&!item.text)description.append(node('p',item.citation));if(item.reason)description.append(node('p',item.reason,'muted'));if(item.candidates?.length)description.append(node('p','Possible sources: '+item.candidates.map(candidate=>candidate.title||'Untitled source').join(' · '),'muted'));row.append(description);if(item.sourceId&&state.project.sources.some(s=>s.id===item.sourceId)){const open=node('button','Open source ↗','text-button');open.addEventListener('click',()=>{capture();state.selected=item.sourceId;state.format=null;renderSources();renderDetail();document.querySelector('.tab[data-view="library"]').click();});row.append(open);}section.append(row);}target.append(section);}
    if(analysis.warnings?.length){const section=node('section',undefined,'audit-section');section.append(node('h3','Additional checks'));for(const warning of analysis.warnings)section.append(node('p',typeof warning==='string'?warning:warning.message,'muted'));target.append(section);}
    target.append(node('p',result.notice||'Plain-text matching is advisory. Review uncertain matches and check cited claims against the original sources. Claim support is not checked.','audit-notice'));
  }
  function showWordStatus(result) {$('word-status').textContent=result?.message||(result?.available?'Word is available. Open your draft to insert citations.':'Open Microsoft Word and a document to continue.');}
  function readWordFormatting() {return {font:$('word-font').value||'Times New Roman',size:Number($('word-size').value)||12,spacing:Number($('word-spacing').value)||2};}
  function renderWordFormatting() {const options=state.project?.wordFormatting||{};for(const [id,key,fallback] of [['word-font','font','Times New Roman'],['word-size','size',12],['word-spacing','spacing',2]]){const select=$(id);const value=String(options[key]||fallback);if(![...select.options].some(option=>option.value===value))select.append(new Option(value,value));select.value=value;}}
  async function confirmAction(title,text,accept='Continue',cancel='Cancel') {$('confirm-title').textContent=title;if(typeof text==='string')$('confirm-text').textContent=text;else $('confirm-text').replaceChildren(text);$('confirm-accept').textContent=accept;$('confirm-cancel').textContent=cancel;$('confirm-dialog').showModal();return new Promise(resolve=>{const finish=value=>{$('confirm-dialog').close();$('confirm-accept').onclick=null;$('confirm-cancel').onclick=null;$('confirm-dialog').onclose=null;resolve(value);};$('confirm-accept').onclick=()=>finish(true);$('confirm-cancel').onclick=()=>finish(false);$('confirm-dialog').onclose=()=>finish(false);});}
  function comparisonText(value) {return String(value||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();}
  function canonicalDOI(s) {let value=String(s.doi||(/^https?:\/\/(?:dx\.)?doi\.org\//i.test(s.url||'')?s.url:'')).trim();try{value=decodeURIComponent(value);}catch{}return value.replace(/^doi\s*:\s*/i,'').replace(/^https?:\/\/(?:dx\.)?doi\.org\//i,'').trim().toLowerCase();}
  function duplicateOf(candidate) {const doi=canonicalDOI(candidate),title=comparisonText(candidate.title),year=comparisonText(candidate.year),authors=comparisonText(authorsText(candidate.authors));return state.project.sources.find(existing=>(doi&&doi===canonicalDOI(existing))||(title&&title===comparisonText(existing.title)&&year===comparisonText(existing.year)&&authors===comparisonText(authorsText(existing.authors))));}
  async function addSource(partial={}) {
    capture();
    const s={type:'journal',authors:[],year:'',title:'',container:'',volume:'',issue:'',pages:'',publisher:'',edition:'',doi:'',url:'',retrieved:'',notes:'',summary:'',content:'',attachments:[],overrides:{},history:[],verification:[],missing:[],...partial};
    const duplicate=duplicateOf(s);
    if(duplicate&&!await confirmAction('This source may already be in your library',`Source ${duplicate.number}, “${duplicate.title||'Untitled source'}”, has the same DOI or publication details. Keep a separate record or skip this addition?`,'Keep separate','Skip duplicate')){toast('Duplicate skipped. Your existing source is unchanged.');return;}
    normalize(state.project);s.type=sourceType(s.type);s.id=crypto.randomUUID();s.number=state.project.nextSourceNumber++;s.include=false;
    state.project.sources.push(s);state.selected=s.id;markDirty();$('add-dialog').close();render();await save();toast('Source added. Check the details and select Include when ready.');
  }
  for(const id of ['create-project','welcome-create'])bind(id,()=>{$('project-dialog').showModal();});
  bind('open-project',async()=>{if(state.aiBusy)throw Error('Wait for GPT before switching projects.');await save();const p=await invoke('openProject');if(p)setProject(p);});
  $('project-create-form').addEventListener('submit',event=>{event.preventDefault();run(event.submitter,async()=>{if(state.aiBusy)throw Error('Wait for GPT before switching projects.');await save();const p=await invoke('createProject',{name:$('new-project-name').value.trim()});if(p){$('project-dialog').close();$('new-project-name').value='';setProject(p);}});});
  all('.dialog-close').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
  for(const id of ['add-source','empty-add'])bind(id,()=>{if(!state.project)throw Error('Open a project first.');$('lookup-error').hidden=true;$('lookup-input').value='';$('add-dialog').showModal();});
  bind('manual-source',()=>addSource());
  $('source-add-form').addEventListener('submit',event=>{event.preventDefault();run(event.submitter,async()=>{const input=$('lookup-input').value.trim();if(!input){$('lookup-error').textContent='Enter a DOI or URL, or choose Add manually.';$('lookup-error').hidden=false;return;}let result;try{result=await invoke('lookup',{input});}catch(error){$('lookup-error').textContent=error.message+' You can still add this source manually.';$('lookup-error').hidden=false;return;}await addSource(result.source||result);});});
  $('source-search').addEventListener('input',renderSources);
  $('metadata-form').addEventListener('submit',e=>e.preventDefault());$('brief-form').addEventListener('submit',e=>e.preventDefault());
  for(const id of ['metadata-form','source-notes','source-summary','source-content','override-reference','override-parenthetical','override-narrative'])$(id).addEventListener('input',()=>{captureSource();markDirty();$('source-title').textContent=source()?.title||'Untitled source';$('source-byline').textContent=source()?authorLine(source()):'';if(source()){$('chat-context').textContent='SOURCE '+source().number+' · '+(source().title||'Untitled');showWarnings(source());}renderSources();});
  $('brief-form').addEventListener('input',event=>{captureBrief();markDirty();if(['question','rubric','draft'].includes(event.target.name))refreshSummaryContextFlags();$('project-title').textContent=state.project.name||'Untitled project';if(source())showWarnings(source());renderProjects();});
  for(const id of ['save-project','source-save','brief-save'])bind(id,async()=>{await save(true);renderHistory();toast('Project saved locally.');});
  all('.tab').forEach(button=>button.addEventListener('click',()=>{capture();all('.tab').forEach(b=>b.classList.toggle('active',b===button));all('.view').forEach(v=>v.classList.toggle('active',v.id===button.dataset.view+'-view'));if(button.dataset.view==='citations'&&state.project)run(null,async()=>{renderCitationSources();await refreshCombined();await refreshBibliography();showWordStatus(await invoke('wordStatus'));});}));
  all('.detail-tabs button').forEach(button=>button.addEventListener('click',()=>{captureSource();all('.detail-tabs button').forEach(b=>b.classList.toggle('active',b===button));all('.detail-page').forEach(p=>p.classList.toggle('active',p.dataset.page===button.dataset.detail));if(button.dataset.detail==='preview')run(null,refreshFormat);if(button.dataset.detail==='history')renderHistory();}));
  bind('source-menu',async()=>{const s=source();if(!s)return;if(state.aiBusy)throw Error('Wait for GPT before removing a source.');if(!await confirmAction('Remove this source?',`Remove “${s.title||'Untitled source'}” from this project? Earlier saved versions remain available in Backups.`, 'Remove source'))return;capture();state.project.sources=state.project.sources.filter(x=>x.id!==s.id);state.ids.delete(s.id);state.selected=state.project.sources[0]?.id||null;markDirty();render();await save();});
  bind('attach',async()=>{if(!source())return;await save();const base=clone(state.project);const result=await invoke('attach',{sourceId:state.selected});if(result?.project){mergeRemote(result.project,base);markDirty();await save();toast('Attachment added to your project.');}});
  bind('refresh-preview',refreshFormat);
  bind('view-evidence',renderEvidence);
  for(const kind of ['reference','parenthetical','narrative'])bind('copy-'+kind,async()=>{await refreshFormat();await copy(state.format[kind],kind==='reference'?state.format.referenceHtml:undefined);});
  for(const id of ['word-font','word-size','word-spacing'])$(id).addEventListener('change',()=>{if(!state.project)return;state.project.wordFormatting=readWordFormatting();markDirty();});
  bind('refresh-bibliography',refreshBibliography);bind('copy-bibliography',async()=>{const b=await refreshBibliography();if(await reviewBibliography(b,'Copy reviewed list'))await copy(b.text,b.html);});
  bind('copy-combined',async()=>{await refreshCombined();await copy(state.combined);});
  bind('insert-combined',async()=>{await refreshCombined();if(!state.combined)throw Error('Select at least one source first.');const result=await invoke('wordInsert',{text:state.combined});if(!result?.canceled)toast('Citation inserted at the Word selection.');});
  bind('export-docx',async()=>{const b=await refreshBibliography();if(!b.text)throw Error('Include at least one source first.');if(!await reviewBibliography(b,'Export reviewed list'))return;const result=await invoke('exportDocx',{html:b.html,text:b.text,...readWordFormatting()});if(result)toast('Word reference file exported.');});
  bind('update-word',async()=>{const b=await refreshBibliography();if(!b.text)throw Error('Include at least one source first.');if(!await reviewBibliography(b,'Update reviewed references'))return;const result=await invoke('wordUpdate',{html:b.html,text:b.text,...readWordFormatting()});if(!result?.canceled){if(result?.hash){state.project.wordState={hash:result.hash,document:result.document,at:new Date().toISOString()};markDirty();await save();}toast(result?.message||'Reference list updated in Word.');}});
  bind('audit-word',async()=>{await save();const result=await invoke('auditWord');renderAudit(result);});
  bind('ai-login',async()=>{const result=await invoke('aiLogin');showAIStatus(result);if(result?.pending)watchAIConnection();toast(result?.message||'Follow the account sign-in instructions.');});
  $('chat-form').addEventListener('submit',event=>{event.preventDefault();run(null,()=>chat());});
  $('chat-input').addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key==='Enter'){event.preventDefault();run(null,()=>chat());}});
  bind('summarize',()=>chat('summary'));
  bind('extract-details',()=>{if(!source())throw Error('Select a source first.');if(!source().content?.trim()&&!source().attachments?.some(a=>a.path&&!a.missing))throw Error('Attach a source file or screenshot, or paste its text, before extracting details.');return chat('chat','Inspect this source’s available content and attached files or screenshots. Extract publication metadata that is explicitly visible or supported by supplied evidence, and offer a metadata correction proposal for my review. Include authors, year/date, title, source type, publication/container, volume, issue, pages, publisher, DOI and URL only where supported. Explain what evidence supports the values and list missing or uncertain fields. Do not invent details or infer publication facts from the file name. Do not apply changes automatically.');});
  bind('dismiss-proposal',()=>{state.proposal=null;$('proposal').hidden=true;});
  bind('apply-proposal',async()=>{if(!state.proposal)return;await save();const base=clone(state.project);const project=await invoke('applyProposal',{proposal:state.proposal});mergeRemote(project,base);state.proposal=null;$('proposal').hidden=true;markDirty();await save();toast('Correction applied and saved in source history.');});
  bind('reveal-project',()=>invoke('revealProject'));
  bind('backup-open',async()=>{await save();const backups=await invoke('backups');$('backups-list').replaceChildren();for(const backup of backups){const row=node('div',undefined,'backup-row'),info=node('div');info.append(node('strong',backup.name),node('small',backup.date?new Date(backup.date).toLocaleString():'Saved version'));const restore=node('button','Restore','secondary small');restore.addEventListener('click',()=>run(restore,async()=>{if(state.aiBusy)throw Error('Wait for GPT before restoring.');await save();const p=await invoke('restore',{name:backup.name});if(p){$('backup-dialog').close();setProject(p);toast('Backup restored.');}}));row.append(info,restore);$('backups-list').append(row);}if(!backups.length)$('backups-list').append(node('p','No earlier versions yet. Backups appear as you save changes.','muted'));$('backup-dialog').showModal();});
  document.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='s'){event.preventDefault();run(null,()=>save(true));}});
  window.addEventListener('beforeunload',event=>{if(state.dirty){event.preventDefault();event.returnValue='Your latest changes are still saving. Use Save now before closing.';run(null,()=>save());}});
  window.refman?.onProgress?.(progress=>{$('ai-status').textContent=typeof progress==='string'?progress:progress?.message||progress?.status||'GPT is working…';});
  run(null,async()=>{const boot=await invoke('boot');state.projects=boot.projects||[];showAIStatus(boot.aiStatus);if(boot.aiStatus?.pending)watchAIConnection();showWordStatus(boot.wordStatus);if(boot.project)setProject(boot.project);else render();});
})();
