const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
let sqlPromise;const getSQL=()=>sqlPromise ||= require('sql.js')({locateFile:f=>require.resolve('sql.js/dist/'+f)});
function atomic(file,data){const tmp=file+'.tmp-'+crypto.randomUUID();let fd;try{fd=fs.openSync(tmp,'wx',0o600);fs.writeFileSync(fd,data);fs.fsyncSync(fd);fs.closeSync(fd);fd=undefined;fs.renameSync(tmp,file);}catch(e){if(fd!==undefined)fs.closeSync(fd);try{fs.unlinkSync(tmp)}catch{}throw e;}}
function validate(p){if(!p||p.schemaVersion!==1||typeof p.id!=='string'||typeof p.name!=='string'||!Array.isArray(p.sources))throw Error('This is not a supported Refman project.');const ids=new Set();for(const s of p.sources){if(!s.id||ids.has(s.id))throw Error('Source identifiers must be unique.');ids.add(s.id);for(const a of s.attachments||[])if(!a.path||path.isAbsolute(a.path)||a.path.split(/[\\/]/).includes('..'))throw Error('An attachment has an unsafe file path.');}return p;}
function readable(p){let t=`REFMAN PROJECT BACKUP\nLast saved: ${p.updatedAt}\nProject: ${p.name}\nPublication range: ${p.minYear}–${p.maxYear} inclusive\n\nASSIGNMENT QUESTION\n${p.question||''}\n\nRUBRIC\n${p.rubric||''}\n\nDRAFT\n${p.draft||''}\n\nSAVED RULES\n${p.rules||''}\n`;for(const s of p.sources)t+=`\n${'='.repeat(65)}\nSOURCE ${s.number}: ${s.title||'Untitled'}\nInclude in references: ${s.include?'Yes':'No'}\n${JSON.stringify(s,null,2)}\n`;try{const c=require('./citations.cjs');t+='\nFORMATTED REFERENCES (SELECTED SOURCES)\n'+c.bibliography(p).text+'\n';for(const source of p.sources){const f=c.formatSource(source,p);t+=`\nSource ${source.number} reference: ${f.reference}\nParenthetical: ${f.parenthetical}\nNarrative: ${f.narrative}\nWarnings: ${(f.warnings||[]).join('; ')}\n`;}}catch(e){t+='\nFormatting unavailable: '+e.message+'\n';}return t+`\nCONVERSATION\n${(p.chat||[]).map(m=>`${m.role}: ${m.content}`).join('\n\n')}\n\nRESTORABLE PROJECT DATA\n---REFMAN-JSON-BEGIN---\n${JSON.stringify(p,null,2)}\n---REFMAN-JSON-END---\n`;}
class Store{
constructor(folder){this.folder=folder;this.project=null;this.saving=Promise.resolve();}
async create(name){fs.mkdirSync(this.folder,{recursive:true});fs.mkdirSync(path.join(this.folder,'attachments'),{recursive:true});fs.mkdirSync(path.join(this.folder,'versions'),{recursive:true});if(fs.existsSync(path.join(this.folder,'project.sqlite')))throw Error('This folder already contains a project.');return this.save({schemaVersion:1,id:crypto.randomUUID(),name,question:'',rubric:'',draft:'',minYear:2019,maxYear:2026,rules:'',sources:[],chat:[],createdAt:new Date().toISOString()});}
async open(){const SQL=await getSQL();const db=new SQL.Database(fs.readFileSync(path.join(this.folder,'project.sqlite')));try{const rows=db.exec('SELECT data FROM project WHERE id=1');if(!rows.length)throw Error('Project database is empty.');this.project=validate(JSON.parse(rows[0].values[0][0]));return structuredClone(this.project);}finally{db.close();}}
save(project){const pending=this.saving.then(()=>this._save(project));this.saving=pending.catch(()=>{});return pending;}
async _save(project){const p=validate(structuredClone(project));p.updatedAt=new Date().toISOString();const contextHash=crypto.createHash('sha256').update([p.question,p.rubric,p.draft].join('\n')).digest('hex');for(const source of p.sources)if(source.summary&&source.summaryContext)source.summaryNeedsRefresh=source.summaryContext!==contextHash;const SQL=await getSQL();fs.mkdirSync(path.join(this.folder,'versions'),{recursive:true});fs.mkdirSync(path.join(this.folder,'attachments'),{recursive:true});if(this.project){atomic(path.join(this.folder,'versions',new Date().toISOString().replace(/[:.]/g,'-')+'-'+crypto.randomUUID().slice(0,8)+'.json'),JSON.stringify(this.project,null,2));}const db=new SQL.Database();let bytes;try{db.run('CREATE TABLE project (id INTEGER PRIMARY KEY, data TEXT NOT NULL)');db.run('INSERT INTO project VALUES (?,?)',[1,JSON.stringify(p)]);bytes=Buffer.from(db.export());}finally{db.close();}atomic(path.join(this.folder,'project.sqlite'),bytes);this.project=p;atomic(path.join(this.folder,'project.json'),JSON.stringify(p,null,2));atomic(path.join(this.folder,'project.txt'),readable(p));return structuredClone(p);}
backups(){return fs.readdirSync(path.join(this.folder,'versions')).filter(f=>f.endsWith('.json')).sort().reverse().map(name=>({name,date:fs.statSync(path.join(this.folder,'versions',name)).mtime.toISOString()}));}
async restore(name){if(path.basename(name)!==name||!name.endsWith('.json'))throw Error('Invalid backup name.');return this.save(validate(JSON.parse(fs.readFileSync(path.join(this.folder,'versions',name),'utf8'))));}
async restoreText(file){return this.restoreFile(file);}
async restoreFile(file){const text=fs.readFileSync(file,'utf8');let p;if(path.extname(file).toLowerCase()==='.json')p=validate(JSON.parse(text));else{const m=text.match(/---REFMAN-JSON-BEGIN---\n([\s\S]*?)\n---REFMAN-JSON-END---/);if(!m)throw Error('No restorable project data found.');p=validate(JSON.parse(m[1]));}p.recoveryWarnings=[];for(const source of p.sources)for(const a of source.attachments||[]){const original=path.resolve(path.dirname(file),a.path);const target=path.join(this.folder,a.path);if(!fs.existsSync(target)){try{const real=fs.realpathSync(original),root=fs.realpathSync(path.dirname(file));if(!real.startsWith(root+path.sep))throw Error('Unsafe original path');fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(real,target,fs.constants.COPYFILE_EXCL);}catch{p.recoveryWarnings.push('Original attachment missing: '+a.name+' (source '+source.number+'). Restore the companion attachments folder.');a.missing=true;}}}return this.save(p);}

async attach(sourceId,file){
 const p=structuredClone(this.project),s=p.sources.find(s=>s.id===sourceId);if(!s)throw Error('Select and save a source first.');
 const ext=path.extname(file).toLowerCase(),relative='attachments/'+crypto.randomUUID()+ext;
 fs.copyFileSync(file,path.join(this.folder,relative),fs.constants.COPYFILE_EXCL);
 const attachment={id:crypto.randomUUID(),name:path.basename(file),path:relative,addedAt:new Date().toISOString()};s.attachments ||= [];s.attachments.push(attachment);
 if(['.pdf','.txt','.docx'].includes(ext))try{
  let text='',basis='';if(ext==='.pdf'){const parsed=await require('pdf-parse')(fs.readFileSync(file));text=parsed.text;attachment.extractedPages=parsed.numpages;basis='PDF text extraction';}
  else if(ext==='.txt'){text=fs.readFileSync(file,'utf8');basis='Text file';}
  else {const parsed=await require('mammoth').extractRawText({path:file});text=parsed.value;basis='Word document text extraction';}
  if(!text.trim())throw Error('No readable text');attachment.contentBasis=basis;s.contentBasis='Attached '+basis;s.content=[s.content||'',text].filter(Boolean).join('\n\n');
 }catch{attachment.extractionWarning='Text could not be extracted; the original is preserved. Paste readable text or attach screenshots of the relevant pages for GPT.';}
 return{project:await this.save(p),attachment};
}
attachmentPath(relative){if(path.isAbsolute(relative)||relative.split(/[\\/]/).includes('..'))throw Error('Invalid attachment path.');const file=fs.realpathSync(path.resolve(this.folder,relative)),root=fs.realpathSync(this.folder);if(!file.startsWith(root+path.sep))throw Error('Attachment outside this project.');return file;}}
module.exports={Store,readable,validate,atomic};
